name: ecommerce_test
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  iconly: ^1.0.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  animate_do: ^3.3.4
  cached_network_image: ^3.4.1
  derry: ^1.5.0
  carousel_slider: ^5.0.0
  zoom_tap_animation: ^1.1.0
  convex_bottom_bar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  freezed: ^2.5.7
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true